apiVersion: v1
kind: Service
metadata:
  name: {{ include "airis-sandbox.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "airis-sandbox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "airis-sandbox.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
